### ISSUE TITLE
startBeakr() defaults

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/beakr#6]
I was surprised that `startBeakr()` appears to default to `daemon = TRUE`.

I think this is not the behavior we want as it requires the user to be familiar with UNIX systems and to trust themselves with killing processes. (I'm still not sure myself about how dangerous `kiilAll()` might be.)

A better default would be `daemon = FALSE` so that development and testing can consist of:
* set a breakpoint in the **beakr** R script
* source the script
* poke at the web page and get dropped into the **beakr** script in debug mode
* walk through the script
* click on the stop button (red square) to have bear shut down

And we need to make sure that this new R6 style documentation mentions the default settings somewhere. I had to experiment and read the source code to understand what the default settings were for `startBeakr`()`.

**Comment by hansmrtn** [comment]
? `startBeakr()` default is `daemon = FALSE`. What version do you have? Documentation updated.
