### ISSUE TITLE
object documentation

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/beakr#8]
Although all the necessary roxygen2 comments seem to be in place, no documentation is shown in RStudio for the objects `Beakr`, `Request`, `Response`, _etc._

We need to figure out how to document R6 objects so that this documentation becomes visible in the installed package.

**Comment by hansmrtn** [comment]
Accessing the documentation of R6 objects differs only slightly from standard functions. You can view the documentation with triple colons as they are not exported variables i.e.  `?beakr:::Beakr`
